export enum PresentationSettingTypes {
  ColumnCount = 'ColumnCount',
  AdvancedSettings = 'AdvancedSettings',
  Hyphens = 'Hyphens',
  FontOverride = 'FontOverride',
  FontSize = 'FontSize',
  FontFamily = 'FontFamily',
  Appearance = 'Appearance',
  View = 'View',
  TextAlign = 'TextAlign',
  WordSpacing = 'WordSpacing',
  LetterSpacing = 'LetterSpacing',
  PageMargins = 'PageMargins',
  LineHeight = 'LineHeight',
  BackgroundColor = 'BackgroundColor',
  TextColor = 'TextColor',
  TypeScale = 'TypeScale',
  ParagraphSpacing = 'ParagraphSpacing',
  ParagraphIndent = 'ParagraphIndent',
}
