export default [
    "ie",
    "eg",
    "ext", // + number?
    "Fig",
    "fig",
    "Figs",
    "figs",
    "et al",
    "Co",
    "Corp",
    "Ave",
    "Inc",
    "Ex",
    "Viz",
    "vs",
    "Vs",
    "repr",
    "Rep",
    "Dem",
    "trans",
    "Vol",
    "pp",
    "rev",
    "est",
    "Ref",
    "Refs",
    "Eq",
    "Eqs",
    "Ch",
    "Sec",
    "Secs",
    "mi",
    "Dept",

    "Univ",
    "Nos",
    "No",
    "Mol",
    "Cell",

    "Miss", "Mrs", "Mr", "Ms",
    "Prof", "Dr",
    "Sgt", "Col", "Gen", "Rep", "Sen",'Gov', "Lt", "Maj", "Capt","St",

    "Sr", "Jr", "jr", "Rev",
    "PhD", "MD", "BA", "MA", "MM",
    "BSc", "MSc",

    "Jan","Feb","Mar","Apr","Jun","Jul","Aug","Sep","Sept","Oct","Nov","Dec",
    "Sun","Mon","Tu","Tue","Tues","Wed","Th","Thu","Thur","Thurs","Fri","Sat"
];
