export enum AccessibilityDisplayString {
    // Ways of Reading
    WaysOfReadingTitle = 'readium.a11y.ways-of-reading-title',
    WaysOfReadingNonvisualReadingAltText = 'readium.a11y.ways-of-reading-nonvisual-reading-alt-text',
    WaysOfReadingNonvisualReadingNoMetadata = 'readium.a11y.ways-of-reading-nonvisual-reading-no-metadata',
    WaysOfReadingNonvisualReadingNone = 'readium.a11y.ways-of-reading-nonvisual-reading-none',
    WaysOfReadingNonvisualReadingNotFully = 'readium.a11y.ways-of-reading-nonvisual-reading-not-fully',
    WaysOfReadingNonvisualReadingReadable = 'readium.a11y.ways-of-reading-nonvisual-reading-readable',
    WaysOfReadingPrerecordedAudioComplementary = 'readium.a11y.ways-of-reading-prerecorded-audio-complementary',
    WaysOfReadingPrerecordedAudioNoMetadata = 'readium.a11y.ways-of-reading-prerecorded-audio-no-metadata',
    WaysOfReadingPrerecordedAudioOnly = 'readium.a11y.ways-of-reading-prerecorded-audio-only',
    WaysOfReadingPrerecordedAudioSynchronized = 'readium.a11y.ways-of-reading-prerecorded-audio-synchronized',
    WaysOfReadingVisualAdjustmentsModifiable = 'readium.a11y.ways-of-reading-visual-adjustments-modifiable',
    WaysOfReadingVisualAdjustmentsUnknown = 'readium.a11y.ways-of-reading-visual-adjustments-unknown',
    WaysOfReadingVisualAdjustmentsUnmodifiable = 'readium.a11y.ways-of-reading-visual-adjustments-unmodifiable',

    // Conformance
    ConformanceTitle = 'readium.a11y.conformance-title',
    ConformanceDetailsTitle = 'readium.a11y.conformance-details-title',
    ConformanceA = 'readium.a11y.conformance-a',
    ConformanceAa = 'readium.a11y.conformance-aa',
    ConformanceAaa = 'readium.a11y.conformance-aaa',
    ConformanceCertifier = 'readium.a11y.conformance-certifier',
    ConformanceCertifierCredentials = 'readium.a11y.conformance-certifier-credentials',
    ConformanceDetailsCertificationInfo = 'readium.a11y.conformance-details-certification-info',
    ConformanceDetailsCertifierReport = 'readium.a11y.conformance-details-certifier-report',
    ConformanceDetailsClaim = 'readium.a11y.conformance-details-claim',
    ConformanceDetailsEpubAccessibility10 = 'readium.a11y.conformance-details-epub-accessibility-1-0',
    ConformanceDetailsEpubAccessibility11 = 'readium.a11y.conformance-details-epub-accessibility-1-1',
    ConformanceDetailsLevelA = 'readium.a11y.conformance-details-level-a',
    ConformanceDetailsLevelAa = 'readium.a11y.conformance-details-level-aa',
    ConformanceDetailsLevelAaa = 'readium.a11y.conformance-details-level-aaa',
    ConformanceDetailsWcag20 = 'readium.a11y.conformance-details-wcag-2-0',
    ConformanceDetailsWcag21 = 'readium.a11y.conformance-details-wcag-2-1',
    ConformanceDetailsWcag22 = 'readium.a11y.conformance-details-wcag-2-2',
    ConformanceNo = 'readium.a11y.conformance-no',
    ConformanceUnknownStandard = 'readium.a11y.conformance-unknown-standard',

    // Navigation
    NavigationTitle = 'readium.a11y.navigation-title',
    NavigationIndex = 'readium.a11y.navigation-index',
    NavigationNoMetadata = 'readium.a11y.navigation-no-metadata',
    NavigationPageNavigation = 'readium.a11y.navigation-page-navigation',
    NavigationStructural = 'readium.a11y.navigation-structural',
    NavigationToc = 'readium.a11y.navigation-toc',

    // Rich Content
    RichContentTitle = 'readium.a11y.rich-content-title',
    RichContentAccessibleChemistryAsLatex = 'readium.a11y.rich-content-accessible-chemistry-as-latex',
    RichContentAccessibleChemistryAsMathml = 'readium.a11y.rich-content-accessible-chemistry-as-mathml',
    RichContentAccessibleMathAsLatex = 'readium.a11y.rich-content-accessible-math-as-latex',
    RichContentAccessibleMathAsMathml = 'readium.a11y.rich-content-accessible-math-as-mathml',
    RichContentAccessibleMathDescribed = 'readium.a11y.rich-content-accessible-math-described',
    RichContentClosedCaptions = 'readium.a11y.rich-content-closed-captions',
    RichContentExtended = 'readium.a11y.rich-content-extended',
    RichContentOpenCaptions = 'readium.a11y.rich-content-open-captions',
    RichContentTranscript = 'readium.a11y.rich-content-transcript',
    RichContentUnknown = 'readium.a11y.rich-content-unknown',

    // Hazards
    HazardsTitle = 'readium.a11y.hazards-title',
    HazardsFlashing = 'readium.a11y.hazards-flashing',
    HazardsFlashingNone = 'readium.a11y.hazards-flashing-none',
    HazardsFlashingUnknown = 'readium.a11y.hazards-flashing-unknown',
    HazardsMotion = 'readium.a11y.hazards-motion',
    HazardsMotionNone = 'readium.a11y.hazards-motion-none',
    HazardsMotionUnknown = 'readium.a11y.hazards-motion-unknown',
    HazardsNoMetadata = 'readium.a11y.hazards-no-metadata',
    HazardsNone = 'readium.a11y.hazards-none',
    HazardsSound = 'readium.a11y.hazards-sound',
    HazardsSoundNone = 'readium.a11y.hazards-sound-none',
    HazardsSoundUnknown = 'readium.a11y.hazards-sound-unknown',
    HazardsUnknown = 'readium.a11y.hazards-unknown',

    // Accessibility Summary
    AccessibilitySummaryTitle = 'readium.a11y.accessibility-summary-title',
    AccessibilitySummaryNoMetadata = 'readium.a11y.accessibility-summary-no-metadata',
    AccessibilitySummaryPublisherContact = 'readium.a11y.accessibility-summary-publisher-contact',

    // Legal Considerations
    LegalConsiderationsTitle = 'readium.a11y.legal-considerations-title',
    LegalConsiderationsExempt = 'readium.a11y.legal-considerations-exempt',
    LegalConsiderationsNoMetadata = 'readium.a11y.legal-considerations-no-metadata',

    // Additional Information
    AdditionalInformationTitle = 'readium.a11y.additional-accessibility-information-title',
    AdditionalInformationAria = 'readium.a11y.additional-accessibility-information-aria',
    AdditionalInformationAudioDescriptions = 'readium.a11y.additional-accessibility-information-audio-descriptions',
    AdditionalInformationBraille = 'readium.a11y.additional-accessibility-information-braille',
    AdditionalInformationColorNotSoleMeansOfConveyingInformation = 'readium.a11y.additional-accessibility-information-color-not-sole-means-of-conveying-information',
    AdditionalInformationDyslexiaReadability = 'readium.a11y.additional-accessibility-information-dyslexia-readability',
    AdditionalInformationFullRubyAnnotations = 'readium.a11y.additional-accessibility-information-full-ruby-annotations',
    AdditionalInformationHighContrastBetweenForegroundAndBackgroundAudio = 'readium.a11y.additional-accessibility-information-high-contrast-between-foreground-and-background-audio',
    AdditionalInformationHighContrastBetweenTextAndBackground = 'readium.a11y.additional-accessibility-information-high-contrast-between-text-and-background',
    AdditionalInformationLargePrint = 'readium.a11y.additional-accessibility-information-large-print',
    AdditionalInformationPageBreaks = 'readium.a11y.additional-accessibility-information-page-breaks',
    AdditionalInformationRubyAnnotations = 'readium.a11y.additional-accessibility-information-ruby-annotations',
    AdditionalInformationSignLanguage = 'readium.a11y.additional-accessibility-information-sign-language',
    AdditionalInformationTactileGraphics = 'readium.a11y.additional-accessibility-information-tactile-graphics',
    AdditionalInformationTactileObjects = 'readium.a11y.additional-accessibility-information-tactile-objects',
    AdditionalInformationTextToSpeechHinting = 'readium.a11y.additional-accessibility-information-text-to-speech-hinting',
    AdditionalInformationUltraHighContrastBetweenTextAndBackground = 'readium.a11y.additional-accessibility-information-ultra-high-contrast-between-text-and-background',
    AdditionalInformationVisiblePageNumbering = 'readium.a11y.additional-accessibility-information-visible-page-numbering',
    AdditionalInformationWithoutBackgroundSounds = 'readium.a11y.additional-accessibility-information-without-background-sounds'
}